apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quickspin-frontend-tls
  namespace: quickspin-frontend
spec:
  dnsNames:
    - app.quickspin.cloud
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-traefik
  secretName: quickspin-frontend-tls
