apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quickspin-frontend-tls
  namespace: quickspin-frontend
spec:
  secretName: quickspin-frontend-tls
  issuerRef:
    name: letsencrypt-prod-traefik
    kind: ClusterIssuer
  dnsNames:
    - app.quickspin.cloud
