apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quickspin-frontend
  namespace: quickspin-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.quickspin.cloud
      secretName: quickspin-frontend-tls
  rules:
    - host: app.quickspin.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quickspin-frontend
                port:
                  number: 80
